name: CI
on: 
    push:
        branches:
            - '*'
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Cache Docker images
              uses: actions/cache@v2
              with:
                path: |
                  ~/.docker
                key: docker-images-${{ runner.os }}-${{ hashFiles('**/Dockerfile') }}
                restore-keys: |
                  docker-images-${{ runner.os }}-
            - name: docker compose up
              run: docker compose up -d --build --wait
            - name: lint php-cs-fixer
              run: docker compose exec php vendor/bin/php-cs-fixer check --diff
            - name: phpstan
              run: docker compose exec php vendor/bin/phpstan analyse
            - name: create DB
              run: docker compose exec php bin/console doctrine:database:create --env=test
            - name: run migrations
              run: docker compose exec php bin/console doctrine:migrations:migrate --no-interaction --env=test
            - name: tests
              run: docker compose exec php php vendor/bin/phpunit
